import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { DeviceWidthProvider } from "@/context/page";
import NextTopLoader from "nextjs-toploader";
import Header from "@/components/Header/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="overflow-x-hidden dark scroll-smooth scrollbar-thin scrollbar-thumb-scrollbarColor !scrollbar-track-transparent scrollbar-rounded-full"
    >
      <body className={`${inter.className} dark overflow-x-hidden`}>
        <NextTopLoader />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <DeviceWidthProvider>
            <Header />
            <main className="mt-16">{children}</main>
          </DeviceWidthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
